version: '3'

services:
  # MYSQL
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: MBAGrupo4
      MYSQL_DATABASE: center
      MYSQL_USER: admin
      MYSQL_PASSWORD: MBAGrupo4
    ports:
      - "3307:3306"   

  # NEST JS - API
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: nestjs-dev-container # Movido para fora do bloco build
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - nodemodules:/app/node_modules     
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"  
    depends_on:
      - database

volumes:
  nodemodules: {}
