version: '3'

services:
    #MYSQL
    database:
       image: mysql:latest
       container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: MBAGrupo4
      MYSQL_DATABASE: center
      MYSQL_USER: admin
      MYSQL_PASSWORD: MBAGrupo4
    ports:
      - "3307:3306"
    volumes:
      - './mysql_data/var/lib/mysql'
    networks:
      - backend